#!/usr/bin/env bash

CWD=$(pwd)
apt-get update

# installing git on the machine

apt-get install git -y

#installing pip for python 2

apt-get install python-pip -y

#installing Django

pip install django

#installing node.js 6.x version
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install nodejs
apt-get install build-essential

# installing pm2 restart
npm install pm2 -g

# installing Grunt.js gloablly
npm install -g grunt-cli

# installing Bower globally
npm install -g bower

# installing ruby and sass
apt-get install ruby-full rubygems -y
gem install sass

# installing redis-server
apt-get install redis-server -y

#installing postgres
apt-get update
apt-get install postgresql postgresql-contrib postgis postgresql-9.5-postgis-2.2 -y
apt-get install libpq-dev python-dev -y
pip install psycopg2

#installing rabbitmq
apt-get install rabbitmq-server -y

#installing uwsgi
pip install uwsgi
mkdir -p /etc/uwsgi/sites
cp -rv $CWD/emperor.uwsgi.service /etc/systemd/system/

#nginx
apt-get install nginx -y

systemctl start emperor.uwsgi.service
systemctl start nginx
systemctl enable nginx
systemctl enable emperor.uwsgi.service
echo "127.0.0.1 micron.dev" >> /etc/hosts




