#!/bin/bash

CWD=$(pwd)
function osm_user(){
	echo "Checking user exists...."
	sudo -H -u postgres bash -c 'psql -c "\du"' | grep osm 
	if [ $? -ne 0 ] ; then
#		echo " creating user.. "
		sudo -H -u postgres bash -c "createuser osm"
	else
		echo "user exists";
#		exit 1;
	fi
}

function osm_database(){
        
	echo "Checking database exists...."
	sudo -H -u postgres bash -c 'psql -c "\l"' | grep  gis
        if [ $? -ne 0 ] ; then
#		echo "creating database...."
                sudo -H -u postgres bash -c "createdb -E UTF8 -O osm gis"
        else
                echo "database exists";
#                exit 1;
        fi
}

function extension_checker(){
	echo "checking extension & creating....."
        sudo -H -u postgres bash -c "psql -c 'CREATE EXTENSION IF NOT EXISTS postgis;' -d gis"
        sudo -H -u postgres bash -c "psql -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -d gis"
}


function check_user(){
	echo "Checking user exists....."
	osm_home="/home/osm"
	if [ ! -d $osm_home ] ; then
#        	echo "creating user...."
		bash -c 'sudo adduser osm --disabled-password --gecos ""'
	else 
		echo " user exists......"
	fi
}

function openstreetcarto(){
	echo "downloading...."
	opencarto="/home/osm/v2.41.0.tar.gz"
	if [ -f $opencarto ] ; then
		echo "file exists...."
	else
		sudo su - osm -c 'wget https://github.com/gravitystorm/openstreetmap-carto/archive/v2.41.0.tar.gz'
		sudo su - osm -c 'tar xvf v2.41.0.tar.gz'
	
		echo "downloaded & extracted...."
	fi
}

function import_map(){
	echo "importing map file"
	sudo -H -u postgres bash -c "psql -d gis -c '\dt'" | grep planet_osm*
	if [ $? -ne 0 ] ; then
		sudo su - osm -c 'osm2pgsql --slim -d gis -C 3600 --hstore -S openstreetmap-carto-2.41.0/openstreetmap-carto.style /home/test/Downloads/ind.pbf'
	else
		echo "already data is in postgres..."
	fi
}

function mod_tile(){
	folder="mod_tile"
	if [ -d $folder ] ; then
		echo " mod folder exists"
	else 
	echo "$CWD"
	sudo git clone https://github.com/openstreetmap/mod_tile.git
	cd mod_tile/
	sudo ./autogen.sh
	sudo ./configure
	sudo make
	sudo make install
	sudo make install-mod_tile
	cd $CWD 
	fi
}

function mapnik(){
	echo "checking mapnik"
	osm_data="/home/osm/data"
	if [ ! -d $osm_data ]; then
		sudo su - osm -c 'exec "$HOME/openstreetmap-carto-2.41.0/get-shapefiles.sh"'
		sudo mv -v /home/osm/data /home/osm/openstreetmap-carto-2.41.0/
		sudo su - osm -c 'carto $HOME/openstreetmap-carto-2.41.0/project.mml > $HOME/openstreetmap-carto-2.41.0/style.xml'
	else
		echo "data exists"
	fi
}

function renderd(){
	sudo sed -i 's/XML=\/home\/jburgess\/osm\/svn\.openstreetmap.org\/applications\/rendering\/mapnik\/osm-local\.xml/XML=\/home\/osm\/openstreetmap-carto-2\.41\.0\/style\.xml/g' /usr/local/etc/renderd.conf
	sudo sed -i 's/HOST=tile\.openstreetmap\.org/HOST=localhost/g' /usr/local/etc/renderd.conf
	sudo sed -i 's/plugins_dir=\/usr\/lib\/mapnik\/input/plugins_dir=\/usr\/lib\/mapnik\/3\.0\/input\//g' /usr/local/etc/renderd.conf

	echo "current path is $(pwd)"
	sudo grep renderd /etc/init.d/renderd
	if [ $? -ne 0 ] ; then
	sudo cp -rv $CWD/mod_tile/debian/renderd.init /etc/init.d/renderd
	sudo chmod a+x /etc/init.d/renderd
	else 
		echo "file exists..."
	fi
}


function changes_renderd(){
	sudo sed -i 's/DAEMON=\/usr\/bin\/\$NAME/DAEMON=\/usr\/local\/bin\/\$NAME/g' /etc/init.d/renderd

	sudo sed -i 's/DAEMON_ARGS=""/DAEMON_ARGS="-c \/usr\/local\/etc\/renderd\.conf"/g' /etc/init.d/renderd
	
	sudo sed -i 's/RUNASUSER=www-data/RUNASUSER=osm/g' /etc/init.d/renderd
	mod="/var/lib/mod_tile"
	if [ ! -d $mod ] ; then
		sudo mkdir -p /var/lib/mod_tile
		sudo chown osm:osm /var/lib/mod_tile
	else 
		echo "mod_tile folder exists....."
	fi
	sudo systemctl daemon-reload
	sudo systemctl start renderd
	
	sudo systemctl enable renderd
	
}

function apache_changes(){
	sed -i 's/Listen.*80/Listen 8080/g' /etc/apache2/ports.conf

	sudo echo -e "LoadModule tile_module /usr/lib/apache2/modules/mod_tile.so" >> /etc/apache2/mods-available/mod_tile.load
	file="/etc/apache2/mods-enabled/mod_tile.load"
	if [ -L $file ] ; then
		echo "sym link exists ...."
	else 
	 	sudo ln -s /etc/apache2/mods-available/mod_tile.load /etc/apache2/mods-enabled/
	fi
	sudo cp -rv $CWD/000-default.conf /etc/apache2/sites-enabled/
	
	sudo systemctl restart apache2
	sudo ldconfig
	sudo systemctl restart renderd.service
}	

function osm_install(){
	echo "starting map install....." $CWD
}


case osm_install in osm_install)
    osm_user
    osm_database
    extension_checker
    check_user
    openstreetcarto
    import_map
    mod_tile
    mapnik
    renderd
    changes_renderd
    apache_changes
    ;;
#    *)
#    usage ;
#    ;;
esac
